name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Create zip file
    - run: zip -r ./module.zip packs module.json README.md CHANGELOG.md LICENSE LICENSE-Oracles

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: './module.zip, module.json'
